### ISSUE TITLE
[Documentation] Small typo: "htslib.cr is the Crystal bindings to HTSlib, a C library for for high-throughput sequencing data formats" has one "for" too many

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/htslib.cr#12]
Hey there kojix2, just a small typo:

"htslib.cr is the [Crystal](https://github.com/crystal-lang/crystal) bindings to [HTSlib](https://github.com/samtools/htslib), a C library for for high-throughput sequencing data formats"

I think you can replace "for for" with just one "for". Hope that typo report is not too annoying for you. :)

**Comment by kojix2** [comment]
You are right. 

Thanks. But I'm surprised you even check out htslib.cr.

But I would have been more than happy if you had sent me a pull request. That is easily done with just a web browser. The more contributors, the better.

**Comment by kojix2** [comment]
I tried adding a co-authored-by comment but it didn't seem to work. Sorry. And thanks.
